### ISSUE TITLE
Getting error while trying to install

### ISSUE THREAD

**Issue by alisterubuntu** [paul-nelson-baker/python-qtest-library#3]
Hi Paul,
Could you please check this error while trying to install 

```
(qtest) alister@alister-Lenovo-ideapad-320-14ISK:~/sample/qtest$ pip install qasymphony-qtest-library
Collecting qasymphony-qtest-library
  Using cached qasymphony_qtest_library-0.2.2-py3-none-any.whl (5.3 kB)
Collecting requests>=2.18.4
  Using cached requests-2.27.1-py2.py3-none-any.whl (63 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2022.5.18.1-py3-none-any.whl (155 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.3-py3-none-any.whl (61 kB)
Collecting charset-normalizer~=2.0.0
  Using cached charset_normalizer-2.0.12-py3-none-any.whl (39 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.9-py2.py3-none-any.whl (138 kB)
Installing collected packages: urllib3, idna, charset-normalizer, certifi, requests, qasymphony-qtest-library
ERROR: Exception:
Traceback (most recent call last):
  File "/home/alister/All Code/qtest/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 164, in exc_logging_wrapper
    status = run_func(*args)
  File "/home/alister/All Code/qtest/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/home/alister/All Code/qtest/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 413, in run
    pycompile=options.compile,
  File "/home/alister/All Code/qtest/lib/python3.7/site-packages/pip/_internal/req/__init__.py", line 81, in install_given_reqs
    pycompile=pycompile,
  File "/home/alister/All Code/qtest/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 771, in install
    prefix=prefix,
  File "/home/alister/All Code/qtest/lib/python3.7/site-packages/pip/_internal/locations/__init__.py", line 214, in get_scheme
    prefix=prefix,
  File "/home/alister/All Code/qtest/lib/python3.7/site-packages/pip/_internal/locations/_distutils.py", line 130, in get_scheme
    scheme = distutils_scheme(dist_name, user, home, root, isolated, prefix)
  File "/home/alister/All Code/qtest/lib/python3.7/site-packages/pip/_internal/locations/_distutils.py", line 46, in distutils_scheme
    d.parse_config_files()
  File "/home/alister/All Code/qtest/lib/python3.7/site-packages/_virtualenv.py", line 21, in parse_config_files
    result = old_parse_config_files(self, *args, **kwargs)
  File "/usr/lib/python3.7/distutils/dist.py", line 397, in parse_config_files
    filenames = self.find_config_files()
  File "/usr/lib/python3.7/distutils/dist.py", line 352, in find_config_files
    sys_dir = os.path.dirname(sys.modules['distutils'].__file__)
  File "/usr/lib/python3.7/posixpath.py", line 156, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
WARNING: You are using pip version 21.3.1; however, version 22.1.2 is available.
You should consider upgrading via the '/home/alister/All Code/qtest/bin/python -m pip install --upgrade pip' command.
(qtest) alister@alister-Lenovo-ideapad-320-14ISK:~/sample/qtest$ 

```

**Comment by nikole-dunixi** [comment]
Hello! Unfortunately, I no longer have the time to maintain this solution. I am going to archive this project so it's still available for reference, but as an alternative browse to their URL (previously [api.qasymphony.com](https://api.qasymphony.com/), but currently [qtest.dev.tricentis.com/](https://qtest.dev.tricentis.com/)) and locate the link to their Python download.

You can view the readme with a screenshot to their download link for clarification.

Good luck!
